<?php $_item = $block->getItem() ?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-wrapper price-including-tax" data-label="<?= /* @escapeNotVerified */ __('Incl. Tax') ?>">
            <?php $_incl = $_item->getPriceInclTax(); ?>
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_incl*$_item->getQty()) ?>
        </span>
<?php endif; ?>
<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-wrapper price-excluding-tax" data-label="<?= /* @escapeNotVerified */ __('Excl. Tax') ?>">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()*$_item->getQty()) ?>
        </span>
<?php endif; ?>
