<?php
/** @var $block \Webbhuset\CollectorCheckout\Block\Admin\OrderInfo */
    $paymentInfo =$block->getPaymentInfo()
?>
<img src="<?=$block->getViewFileUrl('Webbhuset_CollectorCheckout::images/walley.svg')?>" alt="" width="300"/>
<br><br>
<table class="data-grid">
    <thead>
            <tr>
                <th><?=__('Name')?></th>
                <th><?=__('Value')?></th>
            </tr>
        </thead>
    <tbody>
<?php foreach ($paymentInfo as $name => $value) : ?>
    <tr>
        <td>
            <?=$name?>
        </td>
        <td>
            <?=$value?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
