<?php /** @var $block \Webbhuset\CollectorCheckout\Block\Admin\Carrier */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?= /* @escapeNotVerified */ __('Track Order') ?>"><?= /* @escapeNotVerified */ __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /* @escapeNotVerified */ $_excl ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
            <?php endif; ?>
        <?php else: ?>
            <?= /* @escapeNotVerified */ __('No shipping information available') ?>
        <?php endif; ?>
    </div>
    <?php if ($block->isDeliveryCheckoutActive() && !$block->isCustomDeliveryAdapterActive()): ?>
        <?php
            $shippingData = $block->getCarrierInformation();
        ?>
        <br><br>
        <table class="data-grid" style="width:100px">
            <thead>
                <tr>
                    <th><?=__('Name')?></th>
                    <th><?=__('Value')?></th>
                </tr>
            </thead>
        <tbody>
        <?php foreach($shippingData as $field => $value): ?>
            <tr>
                <td>
                    <?=$field?>
                </td>
                <?php if(!is_object($value)) : ?>
                    <td>
                        <?=$value?>
                    </td>
                <?php else: ?>
                    <td>
                    <?php $subShippingData = json_decode(json_encode($value), true);?>
                    <?php foreach ($subShippingData as $subField => $subValue):?>
                        <?=$subField?> = <?=$subValue?>
                    <?php endforeach; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
    <?php endif; ?>
</div>
