<?php
/** @var \Webbhuset\CollectorCheckout\Block\Checkout $block */
$iframe = $block->getIframe();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "collectorIframe": {
                        "component": "collectorIframe",
                        "config":{
                            "src": "<?=$block->escapeUrl($block->getIframeSrc())?>",
                            "dataToken": "<?=$block->escapeHtml($block->getDataToken())?>",
                            "dataVersion": "<?=$block->escapeHtml($block->getDataVersion())?>"
                        }
                    }
                }
            }
        }
    }
</script>
<?php if ($iframe): ?>
    <div data-bind="scope: 'collectorIframe'" id="collectorIframe">
    </div>
<?php else: ?>
    <div id="collectorIframe">
        <?=__('The url is no longer valid')?>;
    </div>
<?php endif; ?>
