<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "collectorSuccess": {
                        "component": "collectorSuccess"
                    }
                }
            }
        }
    }
</script>
<?php
    $iframe = $block->getIframe();
?>

<?php if ($iframe): ?>
    <script>
        window.dataLayer = window.dataLayer || [];
        dataLayer.push(
            <?= $block->getAnalyticsDatalayer() ?>
        );
        dataLayer.push(
            <?= $block->getEnhancedEcommerceDatalayer() ?>
        );
    </script>
    <?= $iframe ?>
<?php else: ?>
<div>
    <?=__('The url is no longer valid')?>
</div>
<?php endif; ?>
